version: "3"

services:
  mongo-primary:
    image: bitnami/mongodb:4.0
    restart: always
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ADVERTISED_HOSTNAME=mongo-primary
      - MONGODB_REPLICA_SET_KEY=repls0
      - MONGODB_ROOT_PASSWORD=s3cr3tp4ss

  mongo-secondary:
    image: bitnami/mongodb:4.0
    depends_on:
          - mongo-primary
    ports:
      - "27018:27017"
    restart: always
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_ADVERTISED_HOSTNAME=mongo-secondary
      - MONGODB_REPLICA_SET_KEY=repls0
      - MONGODB_INITIAL_PRIMARY_HOST=mongo-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=s3cr3tp4ss

  mongo-arbiter:
    image: bitnami/mongodb:4.0
    depends_on:
      - mongo-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_ADVERTISED_HOSTNAME=mongo-arbiter
      - MONGODB_REPLICA_SET_KEY=repls0
      - MONGODB_INITIAL_PRIMARY_HOST=mongo-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=s3cr3tp4ss

volumes:
  mongodb_master_data:
    driver: local